import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { GeneratedDataset } from '../types.js';

export interface SqlExportOptions {
  /** CREATE TABLE DDL to prepend before INSERT statements */
  ddl?: string;
  /** Number of rows per batched INSERT statement (default: 50) */
  batchSize?: number;
  /** Template name for the file header */
  templateName?: string;
}

export async function exportToSql(
  dataset: GeneratedDataset,
  outputDir: string,
  tableOrder: string[],
  options?: SqlExportOptions,
): Promise<string[]> {
  await mkdir(outputDir, { recursive: true });

  const batchSize = options?.batchSize ?? 50;
  const lines: string[] = [];

  // ── File header ──
  lines.push('-- ═══════════════════════════════════════════════════════════════');
  lines.push('-- Generated by RealityDB');
  if (options?.templateName) {
    lines.push(`-- Template: ${options.templateName}`);
  }
  lines.push(`-- Seed: ${dataset.seed}`);
  lines.push(`-- Generated at: ${dataset.generatedAt}`);
  lines.push('-- ═══════════════════════════════════════════════════════════════');
  lines.push('');

  // ── DDL (CREATE TABLE statements) ──
  if (options?.ddl) {
    lines.push('-- ─── SCHEMA ─────────────────────────────────────────────────────');
    lines.push('');
    lines.push(options.ddl);
    lines.push('');
  }

  // ── Data (batched INSERT statements) ──
  lines.push('-- ─── DATA ───────────────────────────────────────────────────────');
  lines.push('');

  for (const tableName of tableOrder) {
    const table = dataset.tables.get(tableName);
    if (!table || table.rows.length === 0) continue;

    const quotedColumns = table.columns.map((c) => `"${c}"`).join(', ');

    // Batch rows into multi-value INSERT statements
    for (let i = 0; i < table.rows.length; i += batchSize) {
      const batch = table.rows.slice(i, i + batchSize);
      const valueRows = batch.map((row) => {
        const values = table.columns.map((col) => escapeSqlValue(row[col])).join(', ');
        return `  (${values})`;
      });

      lines.push(`INSERT INTO "${tableName}" (${quotedColumns}) VALUES`);
      lines.push(valueRows.join(',\n') + ';');
      lines.push('');
    }
  }

  const filePath = join(outputDir, 'seed.sql');
  await writeFile(filePath, lines.join('\n'), 'utf-8');

  return [filePath];
}

function escapeSqlValue(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE';
  }
  // String values — escape single quotes
  const str = String(value);
  return `'${str.replace(/'/g, "''")}'`;
}
