import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { GeneratedDataset } from '../types.js';

export async function exportToSql(
  dataset: GeneratedDataset,
  outputDir: string,
  tableOrder: string[],
): Promise<string[]> {
  await mkdir(outputDir, { recursive: true });

  const lines: string[] = [];
  lines.push('-- Generated by DataBox');
  lines.push(`-- Seed: ${dataset.seed}`);
  lines.push(`-- Generated at: ${dataset.generatedAt}`);
  lines.push('');

  for (const tableName of tableOrder) {
    const table = dataset.tables.get(tableName);
    if (!table || table.rows.length === 0) continue;

    const quotedColumns = table.columns.map((c) => `"${c}"`).join(', ');

    for (const row of table.rows) {
      const values = table.columns.map((col) => escapeSqlValue(row[col])).join(', ');
      lines.push(`INSERT INTO "${tableName}" (${quotedColumns}) VALUES (${values});`);
    }
    lines.push('');
  }

  const filePath = join(outputDir, 'seed.sql');
  await writeFile(filePath, lines.join('\n'), 'utf-8');

  return [filePath];
}

function escapeSqlValue(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE';
  }
  // String values — escape single quotes
  const str = String(value);
  return `'${str.replace(/'/g, "''")}'`;
}
