import * as fs from 'fs';
import * as path from 'path';

export async function ciStartCommand(options: {
  platform?: string;
  pack?: string;
  rows?: string;
  output?: string;
  seed?: string;
  format?: string;
  connectionVar?: string;
}): Promise<void> {
  const platform = options.platform || 'github';
  const pack = options.pack || 'template.json';
  const rows = options.rows || '5000';
  const seed = options.seed || '42';
  const format = options.format || 'sql';
  const connVar = options.connectionVar || 'DATABASE_URL';

  if (!['github', 'gitlab', 'circleci'].includes(platform)) {
    console.error(`\n\u274C Unknown platform: ${platform}`);
    console.error(`   Supported: github, gitlab, circleci`);
    process.exit(1);
  }

  console.log(`\n\u{1F680} RealityDB CI Configuration`);
  console.log(`${'\u2500'.repeat(40)}`);
  console.log(`   Platform: ${platform === 'github' ? 'GitHub Actions' : platform === 'gitlab' ? 'GitLab CI' : 'CircleCI'}`);
  console.log(`   Pack: ${pack}`);
  console.log(`   Rows: ${rows}`);
  console.log(`   Seed: ${seed} (deterministic)`);
  console.log(`   Format: ${format}`);
  console.log(`${'\u2500'.repeat(40)}`);

  let yaml = '';
  let filename = '';

  if (platform === 'github') {
    filename = options.output || '.github/workflows/realitydb-test.yml';
    yaml = `# RealityDB — Ephemeral Test Database for Every PR
# Generated by: realitydb ci start --platform github
# Docs: https://realitydb.dev/docs/ci-cd

name: Test with synthetic data

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

env:
  REALITYDB_SEED: ${seed}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install RealityDB CLI
        run: npm install -g @realitydb/cli@latest

      - name: Generate test data
        run: |
          realitydb run \\
            --pack ${pack} \\
            --rows ${rows} \\
            --seed \${{ env.REALITYDB_SEED }} \\
            --format ${format} \\
            --drop-tables \\
            -o test-seed.${format}

      - name: Seed test database
        if: \${{ '${format}' == 'sql' }}
        env:
          PGPASSWORD: test
        run: |
          psql -h localhost -U test -d test_db -f test-seed.sql

      # Alternative: use realitydb seed directly
      # - name: Seed test database (direct)
      #   run: |
      #     realitydb seed \\
      #       --pack ${pack} \\
      #       --rows ${rows} \\
      #       --seed \${{ env.REALITYDB_SEED }} \\
      #       --connection postgresql://test:test@localhost:5432/test_db \\
      #       --create-tables --drop-tables --batch-size 500

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          ${connVar}: postgresql://test:test@localhost:5432/test_db
        run: npm test

      - name: Run integration tests
        env:
          ${connVar}: postgresql://test:test@localhost:5432/test_db
        run: npm run test:integration || true

    # Postgres service auto-stops after job — no cleanup needed
`;
  } else if (platform === 'gitlab') {
    filename = options.output || '.gitlab-ci.yml';
    yaml = `# RealityDB — Ephemeral Test Database for Every MR
# Generated by: realitydb ci start --platform gitlab
# Docs: https://realitydb.dev/docs/ci-cd

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  REALITYDB_SEED: "${seed}"

stages:
  - test

test:
  stage: test
  image: node:20
  services:
    - postgres:16
  variables:
    ${connVar}: postgresql://test:test@postgres:5432/test_db
  before_script:
    - npm install -g @realitydb/cli@latest
    - npm ci
  script:
    # Generate deterministic test data
    - realitydb run
        --pack ${pack}
        --rows ${rows}
        --seed $REALITYDB_SEED
        --format ${format}
        --drop-tables
        -o test-seed.${format}

    # Seed the database
    - PGPASSWORD=test psql -h postgres -U test -d test_db -f test-seed.${format === 'sql' ? 'sql' : 'sql'}

    # Run tests
    - npm test
    - npm run test:integration || true

  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "main"
`;
  } else if (platform === 'circleci') {
    filename = options.output || '.circleci/config.yml';
    yaml = `# RealityDB — Ephemeral Test Database for Every PR
# Generated by: realitydb ci start --platform circleci
# Docs: https://realitydb.dev/docs/ci-cd

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.0
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db

    environment:
      ${connVar}: postgresql://test:test@localhost:5432/test_db
      REALITYDB_SEED: "${seed}"

    steps:
      - checkout

      - run:
          name: Install RealityDB CLI
          command: npm install -g @realitydb/cli@latest

      - run:
          name: Generate test data
          command: |
            realitydb run \\
              --pack ${pack} \\
              --rows ${rows} \\
              --seed $REALITYDB_SEED \\
              --format ${format} \\
              --drop-tables \\
              -o test-seed.${format}

      - run:
          name: Seed test database
          command: PGPASSWORD=test psql -h localhost -U test -d test_db -f test-seed.sql

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run integration tests
          command: npm run test:integration || true

workflows:
  test:
    jobs:
      - test
`;
  }

  // Write the file
  const outPath = path.resolve(filename);
  const outDir = path.dirname(outPath);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outPath, yaml, 'utf-8');

  console.log(`\n\u2705 CI configuration generated!`);
  console.log(`${'\u2500'.repeat(40)}`);
  console.log(`   \u{1F4C1} File: ${filename}`);
  console.log(`   \u{1F3AF} What it does:`);
  console.log(`      1. Starts a PostgreSQL 16 service`);
  console.log(`      2. Installs @realitydb/cli`);
  console.log(`      3. Generates ${rows} rows (seed: ${seed})`);
  console.log(`      4. Seeds the test database`);
  console.log(`      5. Runs npm test + npm run test:integration`);
  console.log(`\n   \u{1F512} Deterministic: --seed ${seed} = identical data every run`);
  console.log(`   \u{1F504} Auto-cleanup: database destroyed when job ends`);
  console.log(`\n   Next steps:`);
  console.log(`      1. Commit ${filename} to your repo`);
  console.log(`      2. Ensure ${pack} exists in your repo`);
  console.log(`      3. Push — CI runs automatically on PRs`);
  console.log(``);
}
