// apps/cli/src/commands/seed-supabase.ts
// Generates Supabase-compatible seed data
// Three modes:
//   1. --to-file         → writes supabase/seed.sql
//   2. --connection      → direct postgres connection
//   3. --supabase-url    → connects via Supabase credentials

import { loadLicense } from '../auth/license';
import {
  normalizeTables,
  topologicalSort,
  distributeRows,
  generateData,
} from '@realitydb/engine';
import * as fs from 'fs';
import * as path from 'path';
import { buildSupabaseConnectionString } from '../utils/supabase-connection.js';

export interface SeedSupabaseOptions {
  pack: string;
  rows?: string;
  seed?: string;
  batchSize?: string;
  dryRun?: boolean;
  truncate?: boolean;
  toFile?: string;
  connection?: string;
  supabaseUrl?: string;
  supabaseKey?: string;
  dbPassword?: string;    // Supabase database password (Project Settings -> Database)
  createTables?: boolean;
  dropTables?: boolean;
}

function buildConnectionString(opts: SeedSupabaseOptions): string | null {
  if (opts.connection) return opts.connection;
  if (opts.supabaseUrl && (opts.dbPassword || opts.supabaseKey)) {
    // dbPassword is the correct credential for Supavisor; supabaseKey is
    // kept as a fallback for legacy invocations (will fail against Supavisor
    // unless it happens to match the DB password).
    return buildSupabaseConnectionString(opts.supabaseUrl, opts.dbPassword || opts.supabaseKey!);
  }
  return null;
}

function maskConn(conn: string): string {
  return conn.replace(/\/\/([^:]+):([^@]+)@/, '//$1:****@');
}

function formatRows(n: number): string {
  return n.toLocaleString();
}

function buildSupabaseSeedSQL(
  ordered: any[],
  allData: Record<string, any[]>,
  opts: { truncate: boolean; pack: string; rows: number; version: string }
): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push(`-- Generated by RealityDB ${opts.version} on ${now}`);
  lines.push(`-- Pack: ${opts.pack}`);
  lines.push(`-- Rows: ${opts.rows.toLocaleString()}`);
  lines.push(`-- Tables: ${ordered.map(t => t.name).join(', ')}`);
  lines.push(`-- Compatibility: Supabase seed.sql (supabase db reset)`);
  lines.push(`--`);
  lines.push(`-- Usage:`);
  lines.push(`--   Place this file at: supabase/seed.sql`);
  lines.push(`--   Run: supabase db reset`);
  lines.push(``);

  if (opts.truncate) {
    lines.push(`-- Truncate existing data (reverse FK order)`);
    const reversed = [...ordered].reverse();
    for (const table of reversed) {
      lines.push(`TRUNCATE TABLE IF EXISTS "${table.name}" CASCADE;`);
    }
    lines.push(``);
  }

  for (const table of ordered) {
    const rows = allData[table.name];
    if (!rows || rows.length === 0) continue;

    const columns = Object.keys(rows[0]);
    const quotedCols = columns.map((c: string) => `"${c}"`).join(', ');

    lines.push(`-- ${table.name} (${formatRows(rows.length)} rows)`);

    const BATCH = 500;
    for (let offset = 0; offset < rows.length; offset += BATCH) {
      const batch = rows.slice(offset, offset + BATCH);
      const valueRows = batch.map((row: any) => {
        const vals = columns.map((col: string) => {
          const v = row[col];
          if (v === null || v === undefined) return 'NULL';
          if (typeof v === 'number') return String(v);
          if (typeof v === 'boolean') return v ? 'true' : 'false';
          return `'${String(v).replace(/'/g, "''")}'`;
        });
        return `(${vals.join(', ')})`;
      });

      lines.push(`INSERT INTO "${table.name}" (${quotedCols}) VALUES`);
      lines.push(valueRows.join(',\n') + ';');
    }
    lines.push(``);
  }

  return lines.join('\n');
}

export async function seedSupabaseCommand(opts: SeedSupabaseOptions): Promise<void> {
  const license = loadLicense();
  const isLoggedIn = !!license;
  const rows = opts.rows ? parseInt(opts.rows) : 10000;
  const batchSize = opts.batchSize ? parseInt(opts.batchSize) : 100;
  const truncate = opts.truncate ?? false;

  if (isNaN(rows) || rows < 1) {
    console.error(`\n\u274C Invalid row count: ${opts.rows}`);
    process.exit(1);
  }
  if (!isLoggedIn && rows > 50000) {
    console.error(`\n\u274C Free tier limited to 50,000 rows.`);
    console.error(`   Upgrade: realitydb login --api-key YOUR_KEY\n`);
    process.exit(1);
  }

  // Resolve built-in template names the same way `run` does \u2014 e.g.
  // --pack universal instead of requiring the literal dist/packs/universal.json path.
  const BUILT_IN_PACKS: Record<string, string> = {
    universal: 'Universal Starter \u2014 6 cross-industry tables (users, transactions, audit_logs, api_requests, errors, addresses)',
    banking: 'Retail Banking \u2014 16 tables (accounts, transactions, loans, compliance)',
    healthcare: 'Healthcare Analytics \u2014 14 tables (patients, billing, insurance, labs)',
    oncology: 'Oncology Research \u2014 20 tables (patients, treatments, clinical trials)',
    'supply-chain': 'Supply Chain \u2014 24 tables (suppliers, shipments, warehouses)',
    telecom: 'Telecom & Network \u2014 21 tables (subscribers, towers, billing, churn)',
    fintech: 'FinTech Platform \u2014 9 tables (customers, accounts, transactions, fraud)',
    'eu-banking': 'EU Banking \u2014 11 tables (SEPA, PSD2, MiFID II, KYC, AML/SAR)',
    'eu-healthcare': 'EU Healthcare \u2014 14 tables (ICD-10, EHDS, GDPR Art.9)',
    'eu-telecom': 'EU Telecom \u2014 12 tables (BEREC, EECC, GDPR consent)',
    'us-healthcare': 'US Healthcare \u2014 14 tables (ICD-10-CM, MS-DRG, HIPAA)',
    'us-telecom': 'US Telecom \u2014 12 tables (FCC, CCPA/TCPA, CTIA)',
    'us-banking': 'US Banking \u2014 10 tables (ABA routing, FICO, BSA/AML)',
    'us-insurance': 'US Insurance \u2014 11 tables (NAIC, claims, underwriting, reinsurance)',
  };

  if (!opts.pack.includes('/') && !opts.pack.includes('\\') && !opts.pack.endsWith('.json')) {
    const requestedName = opts.pack;
    const packDir = path.resolve(path.dirname(process.argv[1] || __filename), 'packs');
    const bundledPath = path.resolve(packDir, opts.pack + '.json');
    if (fs.existsSync(bundledPath)) {
      opts.pack = bundledPath;
      console.log(`   Using built-in template: ${requestedName in BUILT_IN_PACKS ? requestedName : 'custom'}`);
    } else if (BUILT_IN_PACKS[opts.pack]) {
      const userPackDir = path.resolve(process.env.HOME || process.env.USERPROFILE || '.', '.realitydb', 'templates');
      const userPath = path.resolve(userPackDir, opts.pack + '.json');
      if (fs.existsSync(userPath)) {
        opts.pack = userPath;
      } else {
        console.error(`\n   Template "${opts.pack}" is available but not installed locally.`);
        console.error(`   Download from: https://realitydb-lab-api.eddy-078.workers.dev/v1/store/${opts.pack}`);
        console.error(`   Or install: realitydb store download ${opts.pack}\n`);
        process.exit(1);
      }
    }
  }

  const packPath = path.resolve(opts.pack);
  if (!fs.existsSync(packPath)) {
    console.error(`\n\u274C Pack file not found: ${packPath}`);
    process.exit(1);
  }

  const pack = JSON.parse(fs.readFileSync(packPath, 'utf-8'));
  const { tables, templateName } = normalizeTables(pack);

  if (tables.length === 0) {
    console.error(`\n\u274C No tables found in pack file.`);
    process.exit(1);
  }

  const ordered = topologicalSort(tables);
  const rowsPerTable = distributeRows(ordered, rows);
  const isFileMode = !opts.connection && !opts.supabaseUrl;
  const outputFile = opts.toFile ?? 'supabase/seed.sql';
  const connStr = buildConnectionString(opts);

  console.log(`\n\u{1F680} RealityDB \u2192 Supabase Seed`);
  console.log(`${'─'.repeat(44)}`);
  if (isLoggedIn) {
    console.log(`   User: ${license.email}`);
    console.log(`   Plan: ${license.tier.toUpperCase()}`);
  } else {
    console.log(`   Mode: FREE TIER (50K rows max)`);
  }
  console.log(`   Pack:     ${opts.pack}`);
  console.log(`   Template: ${templateName}`);
  console.log(`   Tables:   ${tables.length}`);
  console.log(`   Rows:     ${formatRows(rows)}`);
  if (isFileMode) {
    console.log(`   Output:   ${outputFile}`);
    console.log(`   Format:   supabase/seed.sql compatible`);
  } else {
    console.log(`   Target:   ${maskConn(connStr!)}`);
  }
  if (truncate) console.log(`   Truncate: yes (TRUNCATE CASCADE before insert)`);
  console.log(`${'─'.repeat(44)}`);

  for (const t of ordered) {
    const fkInfo = t.foreignKeys.length > 0
      ? ` \u2192 refs: ${t.foreignKeys.map((fk: any) => fk.references.table).join(', ')}`
      : ' (root)';
    console.log(`   \u{1F4CA} ${t.name}: ${formatRows(rowsPerTable[t.name])} rows${fkInfo}`);
  }
  console.log(`${'─'.repeat(44)}`);

  console.log(`   Generating data...`);
  const { allData, actualTotal, elapsed } = generateData(ordered, rowsPerTable);
  console.log(`   \u2705 ${formatRows(actualTotal)} rows generated in ${elapsed}s`);

  if (isFileMode) {
    if (opts.dryRun) {
      console.log(`\n\u{1F50D} Dry Run — file would be written to: ${outputFile}`);
      for (const table of ordered) {
        const r = allData[table.name];
        console.log(`   \u{1F4CB} ${table.name}: ${formatRows(r?.length || 0)} rows`);
      }
      console.log(`\n   To generate: remove --dry-run flag\n`);
      return;
    }

    const outDir = path.dirname(path.resolve(outputFile));
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

    console.log(`   Writing ${outputFile}...`);
    const sql = buildSupabaseSeedSQL(ordered, allData, {
      truncate,
      pack: opts.pack,
      rows: actualTotal,
      version: '2.38.0',
    });

    fs.writeFileSync(path.resolve(outputFile), sql, 'utf-8');
    const fileSizeKB = (fs.statSync(path.resolve(outputFile)).size / 1024).toFixed(1);

    console.log(`\n\u2705 Seed file written!`);
    console.log(`${'─'.repeat(44)}`);
    console.log(`   \u{1F4C4} File:   ${outputFile}`);
    console.log(`   \u{1F4E6} Size:   ${fileSizeKB} KB`);
    console.log(`   \u{1F4CA} Rows:   ${formatRows(actualTotal)}`);
    console.log(`   \u23F1\uFE0F  Time:   ${elapsed}s`);
    console.log(``);
    console.log(`   Next steps:`);
    console.log(`   1. cp ${outputFile} supabase/seed.sql`);
    console.log(`   2. supabase db reset`);
    console.log(``);
    console.log(`   Or push to remote Supabase:`);
    console.log(`   psql [connection-string] -f ${outputFile}`);
    console.log(``);
    return;
  }

  if (!connStr) {
    console.error(`\n\u274C No connection method provided.`);
    console.error(`   Use one of:`);
    console.error(`   --to-file supabase/seed.sql`);
    console.error(`   --connection postgresql://...`);
    console.error(`   --supabase-url https://[ref].supabase.co --db-password [db_password]`);
    console.error(``);
    console.error(`   Requires two Supabase credentials:`);
    console.error(`     --supabase-key: your anon or service_role API key (Supabase API authentication)`);
    console.error(`     --db-password:  your database password (Project Settings \u2192 Database \u2192 Connection string)`);
    console.error(`                     This is NOT the same as your service_role key.`);
    process.exit(1);
  }

  if (opts.dryRun) {
    console.log(`\n\u{1F50D} Dry Run — would connect to: ${maskConn(connStr)}`);
    for (const table of ordered) {
      const r = allData[table.name];
      console.log(`   \u{1F4CB} ${table.name}: ${formatRows(r?.length || 0)} rows would be inserted`);
    }
    console.log(`\n   To execute: remove --dry-run flag\n`);
    return;
  }

  let pg: any;
  try {
    pg = await import('pg');
  } catch {
    console.error(`\n\u274C PostgreSQL driver not found. Run: npm install pg`);
    process.exit(1);
  }

  const client = new pg.Client({ connectionString: connStr });

  try {
    console.log(`   Connecting...`);
    await client.connect();
    console.log(`   \u2705 Connected to Supabase`);

    if (opts.dropTables) {
      console.log(`   Dropping tables...`);
      for (let i = ordered.length - 1; i >= 0; i--) {
        await client.query(`DROP TABLE IF EXISTS "${ordered[i].name}" CASCADE`);
      }
      console.log(`   \u2705 Tables dropped`);
    }

    if (opts.createTables || opts.dropTables) {
      console.log(`   Creating tables...`);
      const { generateCreateTable } = await import('@realitydb/engine');
      for (const table of ordered) {
        await client.query(generateCreateTable(table));
      }
      console.log(`   \u2705 ${ordered.length} tables created`);
    }

    if (truncate && !opts.dropTables) {
      console.log(`   Truncating...`);
      for (const table of [...ordered].reverse()) {
        await client.query(`TRUNCATE TABLE IF EXISTS "${table.name}" CASCADE`);
      }
      console.log(`   \u2705 Tables truncated`);
    }

    console.log(`   Inserting data...`);
    const insertStart = Date.now();
    let totalInserted = 0;

    for (const table of ordered) {
      const tableData = allData[table.name];
      if (!tableData || tableData.length === 0) continue;
      const columns = Object.keys(tableData[0]);
      let tableInserted = 0;

      for (let offset = 0; offset < tableData.length; offset += batchSize) {
        const batch = tableData.slice(offset, offset + batchSize);
        const values: any[] = [];
        const rowPlaceholders: string[] = [];

        for (let rowIdx = 0; rowIdx < batch.length; rowIdx++) {
          const row = batch[rowIdx];
          const placeholders: string[] = [];
          for (let colIdx = 0; colIdx < columns.length; colIdx++) {
            placeholders.push(`$${rowIdx * columns.length + colIdx + 1}`);
            values.push(row[columns[colIdx]]);
          }
          rowPlaceholders.push(`(${placeholders.join(', ')})`);
        }

        const quotedCols = columns.map((c: string) => `"${c}"`).join(', ');
        await client.query(
          `INSERT INTO "${table.name}" (${quotedCols}) VALUES ${rowPlaceholders.join(', ')}`,
          values
        );
        tableInserted += batch.length;
      }

      totalInserted += tableInserted;
      console.log(`   \u{1F4CA} ${table.name}: ${formatRows(tableInserted)} rows inserted`);
    }

    const insertElapsed = ((Date.now() - insertStart) / 1000).toFixed(2);
    console.log(`\n\u2705 Seed complete!`);
    console.log(`${'─'.repeat(44)}`);
    console.log(`   \u{1F4CA} Total:  ${formatRows(totalInserted)} rows`);
    console.log(`   \u23F1\uFE0F  Generate: ${elapsed}s`);
    console.log(`   \u23F1\uFE0F  Insert:   ${insertElapsed}s`);
    console.log(`   \u{1F4C8} Speed:  ${Math.round(totalInserted / parseFloat(insertElapsed)).toLocaleString()} rows/sec`);
    console.log(``);

  } catch (error: any) {
    console.error(`\n\u274C Seed failed: ${error.message}`);
    if (error.message.includes('ECONNREFUSED')) {
      console.error(`   Hint: Is your Supabase project running? Check: supabase status`);
    } else if (error.message.includes('does not exist')) {
      console.error(`   Hint: Add --create-tables to create the schema first`);
    } else if (error.message.includes('already exists')) {
      console.error(`   Hint: Add --truncate to clear existing data first`);
    } else if (error.message.includes('ENOTFOUND') || error.message.includes('tenant')) {
      console.error(`   Hint: This usually means --db-password is missing or wrong.`);
      console.error(`   Supavisor authenticates with your DATABASE password, not your API key.`);
      console.error(`   Get it: Supabase Dashboard \u2192 Settings \u2192 Database \u2192 Connection string`);
    } else if (error.message.includes('authentication')) {
      console.error(`   Hint: Use --db-password (Project Settings \u2192 Database), not --supabase-key`);
      console.error(`   Get it: Supabase Dashboard \u2192 Settings \u2192 Database \u2192 Connection string`);
    }
    process.exit(1);
  } finally {
    await client.end();
  }
}