const fs = require('fs');
const path = require('path');
const BATCH_SIZE = 50;
function mapDataType(col) {
  const dt = (col.dataType || '').toLowerCase();
  if (dt === 'uuid') return 'UUID';
  if (dt.includes('character varying') || dt === 'varchar') return col.maxLength ? 'VARCHAR(' + col.maxLength + ')' : 'VARCHAR(255)';
  if (dt === 'text') return 'TEXT';
  if (dt === 'integer' || dt === 'int' || dt === 'int4') return 'INTEGER';
  if (dt === 'bigint' || dt === 'int8') return 'BIGINT';
  if (dt === 'smallint') return 'SMALLINT';
  if (dt === 'numeric' || dt === 'decimal') return col.numericPrecision ? 'NUMERIC(' + col.numericPrecision + ',' + (col.numericScale||0) + ')' : 'NUMERIC';
  if (dt === 'real' || dt === 'float4') return 'REAL';
  if (dt === 'double precision') return 'DOUBLE PRECISION';
  if (dt === 'boolean' || dt === 'bool') return 'BOOLEAN';
  if (dt.includes('timestamp')) return 'TIMESTAMPTZ';
  if (dt === 'date') return 'DATE';
  if (dt === 'jsonb') return 'JSONB';
  if (dt === 'json') return 'JSON';
  return 'VARCHAR(255)';
}
function escapeValue(val, dataType) {
  if (val === null || val === undefined) return 'NULL';
  const dt = (dataType || '').toLowerCase();
  if (dt === 'boolean' || dt === 'bool') return (val === true || val === 'true') ? 'true' : 'false';
  if (['integer','int','int4','bigint','int8','smallint','numeric','decimal','real','float4','double precision'].some(t => dt.includes(t))) {
    const num = Number(val);
    return isNaN(num) ? 'NULL' : String(val);
  }
  if (dt === 'jsonb' || dt === 'json') {
    const s = typeof val === 'string' ? val : JSON.stringify(val);
    return "'" + s.replace(/'/g, "''") + "'";
  }
  return "'" + String(val).replace(/'/g, "''") + "'";
}
function topologicalSort(tables) {
  const names = new Set(tables.map(t => t.name));
  const deps = new Map();
  for (const t of tables) {
    const d = new Set();
    if (t.foreignKeys) for (const fk of t.foreignKeys) {
      const ref = fk.referencedTable || fk.references;
      if (ref && names.has(ref) && ref !== t.name) d.add(ref);
    }
    deps.set(t.name, d);
  }
  const sorted = [], visited = new Set(), visiting = new Set();
  function visit(n) {
    if (visited.has(n)) return;
    if (visiting.has(n)) return;
    visiting.add(n);
    for (const d of (deps.get(n) || [])) visit(d);
    visiting.delete(n); visited.add(n); sorted.push(n);
  }
  for (const t of tables) visit(t.name);
  const m = new Map(tables.map(t => [t.name, t]));
  return sorted.map(n => m.get(n)).filter(Boolean);
}
const args = process.argv.slice(2);
if (!args[0]) { console.error('Usage: node pack-to-sql.js <input.json> [output.sql]'); process.exit(1); }
const pack = JSON.parse(fs.readFileSync(path.resolve(args[0]), 'utf-8'));
const lines = [];
lines.push('-- Generated by RealityDB pack-to-sql');
lines.push('-- Template: ' + (pack.metadata?.templateName || 'unknown'));
lines.push('-- Seed: ' + (pack.metadata?.seed || 42));
lines.push('-- Generated: ' + new Date().toISOString());
lines.push('');
const schemaTables = pack.schema?.tables || [];
const dataMap = new Map();
const ds = pack.dataset?.tables || pack.data?.tables || {};
if (Array.isArray(ds)) { for (const d of ds) dataMap.set(d.name, d.rows || []); }
else { for (const [n, d] of Object.entries(ds)) dataMap.set(n, d.rows || d.data || []); }
const withData = schemaTables.filter(t => dataMap.has(t.name) && dataMap.get(t.name).length > 0);
const sorted = topologicalSort(withData);
lines.push('-- SCHEMA');
lines.push('');
for (const table of sorted) {
  const colDefs = table.columns.map(c => '  "' + c.name + '" ' + mapDataType(c) + (c.nullable === false ? ' NOT NULL' : ''));
  const pk = table.columns.find(c => c.name === 'id');
  if (pk) colDefs.push('  PRIMARY KEY ("id")');
  if (table.foreignKeys) for (const fk of table.foreignKeys) {
    const ref = fk.referencedTable || fk.references;
    const col = fk.column || fk.localColumn;
    if (ref && col) colDefs.push('  FOREIGN KEY ("' + col + '") REFERENCES "' + ref + '" ("' + (fk.referencedColumn || 'id') + '")');
  }
  lines.push('CREATE TABLE IF NOT EXISTS "' + table.name + '" (');
  lines.push(colDefs.join(',\n'));
  lines.push(');\n');
}
lines.push('-- DATA');
lines.push('');
for (const table of sorted) {
  const rows = dataMap.get(table.name) || [];
  if (!rows.length) continue;
  const cols = table.columns.map(c => c.name);
  const types = new Map(table.columns.map(c => [c.name, c.dataType || 'varchar']));
  const qc = cols.map(c => '"' + c + '"').join(', ');
  lines.push('-- ' + table.name + ': ' + rows.length + ' rows');
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    lines.push('INSERT INTO "' + table.name + '" (' + qc + ') VALUES');
    const vals = batch.map(row => '  (' + cols.map(c => escapeValue(row[c], types.get(c))).join(', ') + ')');
    lines.push(vals.join(',\n') + ';');
    lines.push('');
  }
}
const out = lines.join('\n');
if (args[1]) {
  fs.writeFileSync(path.resolve(args[1]), out, 'utf-8');
  const sz = (Buffer.byteLength(out) / 1024 / 1024).toFixed(2);
  const rc = Array.from(dataMap.values()).reduce((s, r) => s + r.length, 0);
  console.log('Done: ' + args[1]);
  console.log('  Tables: ' + sorted.length + ' | Rows: ' + rc.toLocaleString() + ' | Size: ' + sz + ' MB');
} else { process.stdout.write(out); }