export interface SuggestedQuery {
  label: string;
  sql: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  concept: string;
  // Grading fields
  checkable?: boolean;
  requiredClauses?: string[];
  checkOrder?: boolean;
  trapHint?: string;
  correctHint?: string;
}

export interface Template {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  tables: string[];
  rowsPerTable: number;
  suggestedQueries: SuggestedQuery[];
}

export const templates: Template[] = [
  {
    id: 'saas',
    name: 'SaaS Startup',
    description: 'Multi-tenant SaaS platform with organizations, users, plans, subscriptions, and billing.',
    icon: '\u{1F680}',
    category: 'STARTUP',
    tables: ['organizations', 'users', 'plans', 'subscriptions'],
    rowsPerTable: 15,
    suggestedQueries: [
      {
        label: 'Count users by plan',
        sql: `SELECT p.name AS plan, COUNT(s.id) AS subscriptions FROM plans p LEFT JOIN subscriptions s ON p.id = s.plan_id GROUP BY p.name ORDER BY subscriptions DESC`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
      },
      {
        label: 'Users with org names',
        sql: `SELECT u.full_name, u.email, o.name AS organization FROM users u JOIN organizations o ON u.org_id = o.id ORDER BY o.name`,
        difficulty: 'beginner',
        concept: 'JOIN',
      },
      {
        label: 'Challenge: Plans with no subscribers',
        sql: `SELECT p.name AS plan, p.price_cents / 100.0 AS price\nFROM plans p\nLEFT JOIN subscriptions s ON p.id = s.plan_id\nWHERE s.id IS NULL\nORDER BY p.name;`,
        difficulty: 'intermediate',
        concept: 'LEFT JOIN + IS NULL',
        checkable: true,
        requiredClauses: ['LEFT JOIN', 'IS NULL'],
        trapHint: 'If you used INNER JOIN or NOT IN, you may get incorrect results or miss edge cases. Use LEFT JOIN with IS NULL to find plans that have zero subscriptions.',
        correctHint: 'Correct! LEFT JOIN + IS NULL is the standard anti-join pattern for finding unmatched rows.',
      },
      {
        label: 'Challenge: Revenue by plan (include free plans)',
        sql: `SELECT p.name AS plan, p.price_cents / 100.0 AS price, COUNT(s.id) AS subscribers, (p.price_cents * COUNT(s.id)) / 100.0 AS total_revenue FROM plans p LEFT JOIN subscriptions s ON p.id = s.plan_id GROUP BY p.name, p.price_cents ORDER BY total_revenue DESC`,
        difficulty: 'intermediate',
        concept: 'aggregation',
        checkable: true,
        requiredClauses: ['LEFT JOIN', 'GROUP BY'],
        checkOrder: true,
        trapHint: 'If you used JOIN instead of LEFT JOIN, free plans with zero subscribers will be missing from your results. Make sure every plan appears in the output.',
        correctHint: 'You correctly used LEFT JOIN to include all plans, even those with no subscribers. COUNT(s.id) returns 0 for unmatched rows.',
      },
      {
        label: 'Active subscriptions',
        sql: `SELECT s.*, p.name AS plan_name FROM subscriptions s JOIN plans p ON s.plan_id = p.id WHERE s.status = 'active'`,
        difficulty: 'beginner',
        concept: 'WHERE',
      },
    ],
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Store',
    description: 'Online retail platform with customers, products, orders, and reviews.',
    icon: '\u{1F6D2}',
    category: 'COMMERCE',
    tables: ['customers', 'categories', 'products', 'orders', 'order_items', 'reviews'],
    rowsPerTable: 20,
    suggestedQueries: [
      {
        label: 'Orders by status',
        sql: `SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status ORDER BY order_count DESC`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
      },
      {
        label: 'Challenge: Customer spending (all customers)',
        sql: `SELECT c.first_name || ' ' || c.last_name AS customer, COUNT(o.id) AS orders, COALESCE(SUM(o.total_cents), 0) / 100.0 AS total_spent FROM customers c LEFT JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name ORDER BY total_spent DESC`,
        difficulty: 'intermediate',
        concept: 'JOIN+aggregation',
        checkable: true,
        requiredClauses: ['LEFT JOIN', 'GROUP BY'],
        checkOrder: true,
        trapHint: 'Your results are missing customers who never placed an order. Use LEFT JOIN instead of JOIN, and COALESCE to handle NULL sums.',
        correctHint: 'Correct! LEFT JOIN includes all customers, and COALESCE handles NULL sums for customers with zero orders.',
      },
      {
        label: 'Shipping performance',
        sql: `SELECT status, COUNT(*) AS count, ROUND(AVG(EXTRACT(EPOCH FROM (delivered_at - ordered_at)) / 86400), 1) AS avg_days FROM orders WHERE delivered_at IS NOT NULL GROUP BY status`,
        difficulty: 'intermediate',
        concept: 'date functions',
      },
      {
        label: 'Challenge: Products with no reviews',
        sql: `SELECT p.name, p.price\nFROM products p\nLEFT JOIN reviews r ON p.id = r.product_id\nWHERE r.id IS NULL\nORDER BY p.name;`,
        difficulty: 'intermediate',
        concept: 'LEFT JOIN anti-pattern',
        checkable: true,
        requiredClauses: ['LEFT JOIN', 'IS NULL'],
        trapHint: 'Using NOT IN or INNER JOIN will not correctly find products without reviews. Use LEFT JOIN with WHERE r.id IS NULL to find unmatched products.',
        correctHint: 'Correct! The LEFT JOIN + IS NULL anti-join pattern is the standard way to find rows with no matching counterpart.',
      },
    ],
  },
  {
    id: 'fintech',
    name: 'FinTech Payments',
    description: 'Payment processing platform with accounts, transactions, fraud detection, and settlements.',
    icon: '\u{1F4B0}',
    category: 'FINANCE',
    tables: ['accounts', 'transactions', 'fraud_alerts', 'settlements', 'chargebacks'],
    rowsPerTable: 15,
    suggestedQueries: [
      {
        label: 'Transactions by type',
        sql: `SELECT type, COUNT(*) AS tx_count, SUM(amount_cents) / 100.0 AS total_amount FROM transactions GROUP BY type ORDER BY total_amount DESC`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
      },
      {
        label: 'Account balances with fraud count',
        sql: `SELECT a.name, a.balance_cents / 100.0 AS balance, COUNT(f.id) AS fraud_alerts FROM accounts a LEFT JOIN transactions t ON a.id = t.account_id LEFT JOIN fraud_alerts f ON t.id = f.transaction_id GROUP BY a.id, a.name, a.balance_cents ORDER BY fraud_alerts DESC`,
        difficulty: 'intermediate',
        concept: 'JOIN+aggregation',
      },
      {
        label: 'High-value transactions',
        sql: `SELECT t.id, a.name AS account, t.type, t.amount_cents / 100.0 AS amount, t.status, t.created_at FROM transactions t JOIN accounts a ON t.account_id = a.id WHERE t.amount_cents > 50000 ORDER BY t.amount_cents DESC`,
        difficulty: 'beginner',
        concept: 'WHERE+JOIN',
      },
      {
        label: 'Settlement summary',
        sql: `SELECT s.status, COUNT(*) AS count, SUM(s.amount_cents) / 100.0 AS total_settled FROM settlements s GROUP BY s.status ORDER BY total_settled DESC`,
        difficulty: 'beginner',
        concept: 'aggregation',
      },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare System',
    description: 'Electronic health records with patients, providers, encounters, diagnoses, and billing.',
    icon: '\u{1F3E5}',
    category: 'HEALTH',
    tables: ['patients', 'providers', 'encounters', 'diagnoses', 'billing', 'medications', 'vitals'],
    rowsPerTable: 15,
    suggestedQueries: [
      {
        label: 'Challenge: Encounters by provider (include all)',
        sql: `SELECT p.first_name || ' ' || p.last_name AS provider, p.specialty, COUNT(e.id) AS encounters FROM providers p LEFT JOIN encounters e ON p.id = e.provider_id GROUP BY p.id, p.first_name, p.last_name, p.specialty ORDER BY encounters DESC`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
        checkable: true,
        requiredClauses: ['LEFT JOIN', 'GROUP BY'],
        checkOrder: true,
        trapHint: 'If you used JOIN instead of LEFT JOIN, providers with zero encounters will be missing. Use LEFT JOIN and COUNT(e.id) to include all providers.',
        correctHint: 'Correct! LEFT JOIN ensures all providers appear, even those with no encounters yet.',
      },
      {
        label: 'Patient medications with diagnoses',
        sql: `SELECT pt.first_name || ' ' || pt.last_name AS patient, m.name AS medication, m.dosage, d.code AS diagnosis_code, d.description AS diagnosis FROM medications m JOIN patients pt ON m.patient_id = pt.id JOIN diagnoses d ON m.diagnosis_id = d.id ORDER BY pt.last_name`,
        difficulty: 'intermediate',
        concept: 'multi-table JOIN',
      },
      {
        label: 'Challenge: Billing summary by status',
        sql: `SELECT b.status, COUNT(*) AS claims, SUM(b.amount_cents) / 100.0 AS total_amount, ROUND(AVG(b.amount_cents) / 100.0, 2) AS avg_amount FROM billing b GROUP BY b.status ORDER BY total_amount DESC`,
        difficulty: 'beginner',
        concept: 'aggregation',
        checkable: true,
        requiredClauses: ['GROUP BY'],
        checkOrder: true,
        trapHint: 'Make sure you are grouping by status and ordering by total_amount descending. Check that your column aliases match.',
        correctHint: 'Correct! You properly aggregated billing data by status with accurate totals and averages.',
      },
      {
        label: 'Recent vitals by patient',
        sql: `SELECT pt.first_name || ' ' || pt.last_name AS patient, v.heart_rate, v.systolic_bp, v.diastolic_bp, v.temperature, v.recorded_at FROM vitals v JOIN patients pt ON v.patient_id = pt.id ORDER BY v.recorded_at DESC LIMIT 20`,
        difficulty: 'beginner',
        concept: 'JOIN+ORDER BY',
      },
    ],
  },
  {
    id: 'logistics',
    name: 'Logistics & Supply Chain',
    description: 'Warehouse and shipping management with inventory tracking and route optimization.',
    icon: '\u{1F4E6}',
    category: 'OPERATIONS',
    tables: ['warehouses', 'shipments', 'inventory', 'routes'],
    rowsPerTable: 15,
    suggestedQueries: [
      {
        label: 'Inventory by warehouse',
        sql: `SELECT w.name AS warehouse, w.city, COUNT(i.id) AS items, SUM(i.quantity) AS total_units FROM warehouses w LEFT JOIN inventory i ON w.id = i.warehouse_id GROUP BY w.id, w.name, w.city ORDER BY total_units DESC`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
      },
      {
        label: 'Shipment status overview',
        sql: `SELECT s.status, COUNT(*) AS shipment_count, ROUND(AVG(s.weight_kg), 1) AS avg_weight FROM shipments s GROUP BY s.status ORDER BY shipment_count DESC`,
        difficulty: 'beginner',
        concept: 'aggregation',
      },
      {
        label: 'Route efficiency',
        sql: `SELECT r.origin, r.destination, r.distance_km, COUNT(s.id) AS shipments, ROUND(AVG(EXTRACT(EPOCH FROM (s.delivered_at - s.shipped_at)) / 3600), 1) AS avg_hours FROM routes r LEFT JOIN shipments s ON r.id = s.route_id WHERE s.delivered_at IS NOT NULL GROUP BY r.id, r.origin, r.destination, r.distance_km ORDER BY avg_hours ASC`,
        difficulty: 'intermediate',
        concept: 'JOIN+date functions',
      },
      {
        label: 'Low stock items',
        sql: `SELECT i.product_name, w.name AS warehouse, i.quantity, i.reorder_level FROM inventory i JOIN warehouses w ON i.warehouse_id = w.id WHERE i.quantity <= i.reorder_level ORDER BY i.quantity ASC`,
        difficulty: 'beginner',
        concept: 'WHERE+JOIN',
      },
    ],
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity Operations',
    description: 'Security operations center with asset tracking, vulnerability management, and incident response.',
    icon: '\u{1F512}',
    category: 'SECURITY',
    tables: ['assets', 'vulnerabilities', 'incidents', 'scan_results'],
    rowsPerTable: 15,
    suggestedQueries: [
      {
        label: 'Vulnerabilities by severity',
        sql: `SELECT severity, COUNT(*) AS vuln_count FROM vulnerabilities GROUP BY severity ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 END`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
      },
      {
        label: 'Assets with open incidents',
        sql: `SELECT a.hostname, a.ip_address, a.asset_type, COUNT(i.id) AS open_incidents FROM assets a JOIN incidents i ON a.id = i.asset_id WHERE i.status = 'open' GROUP BY a.id, a.hostname, a.ip_address, a.asset_type ORDER BY open_incidents DESC`,
        difficulty: 'intermediate',
        concept: 'JOIN+aggregation',
      },
      {
        label: 'Recent scan findings',
        sql: `SELECT sr.scanned_at, a.hostname, v.cve_id, v.severity, sr.status FROM scan_results sr JOIN assets a ON sr.asset_id = a.id JOIN vulnerabilities v ON sr.vulnerability_id = v.id ORDER BY sr.scanned_at DESC LIMIT 20`,
        difficulty: 'beginner',
        concept: 'multi-table JOIN',
      },
      {
        label: 'Incident response times',
        sql: `SELECT i.severity, COUNT(*) AS incidents, ROUND(AVG(EXTRACT(EPOCH FROM (i.resolved_at - i.created_at)) / 3600), 1) AS avg_resolution_hours FROM incidents i WHERE i.resolved_at IS NOT NULL GROUP BY i.severity ORDER BY avg_resolution_hours DESC`,
        difficulty: 'intermediate',
        concept: 'date functions+aggregation',
      },
    ],
  },
  {
    id: 'ai-events',
    name: 'AI/ML Platform',
    description: 'Machine learning operations platform with model tracking, experiments, deployments, and event logging.',
    icon: '\u{1F916}',
    category: 'AI/ML',
    tables: ['models', 'experiments', 'deployments', 'events'],
    rowsPerTable: 15,
    suggestedQueries: [
      {
        label: 'Models by framework',
        sql: `SELECT framework, COUNT(*) AS model_count, ROUND(AVG(accuracy * 100), 1) AS avg_accuracy_pct FROM models GROUP BY framework ORDER BY model_count DESC`,
        difficulty: 'beginner',
        concept: 'GROUP BY',
      },
      {
        label: 'Experiment results by model',
        sql: `SELECT m.name AS model, m.framework, COUNT(e.id) AS experiments, ROUND(MAX(e.metric_value), 4) AS best_metric FROM models m JOIN experiments e ON m.id = e.model_id GROUP BY m.id, m.name, m.framework ORDER BY best_metric DESC`,
        difficulty: 'intermediate',
        concept: 'JOIN+aggregation',
      },
      {
        label: 'Active deployments',
        sql: `SELECT d.environment, m.name AS model, d.status, d.replicas, d.created_at FROM deployments d JOIN models m ON d.model_id = m.id WHERE d.status = 'active' ORDER BY d.created_at DESC`,
        difficulty: 'beginner',
        concept: 'WHERE+JOIN',
      },
      {
        label: 'Event volume by type',
        sql: `SELECT event_type, COUNT(*) AS event_count, MIN(created_at) AS first_event, MAX(created_at) AS last_event FROM events GROUP BY event_type ORDER BY event_count DESC`,
        difficulty: 'beginner',
        concept: 'aggregation',
      },
    ],
  },
  {
    id: 'sql-traps',
    name: 'SQL Debugging Challenge',
    description: 'Intentionally tricky data with 10 query traps across 8 tables. Learn by debugging.',
    icon: '\u{1FAA4}',
    category: 'LEARNING',
    tables: ['suppliers', 'customers', 'products', 'orders', 'order_items', 'reviews', 'inventory_log', 'customer_events'],
    rowsPerTable: 1578,
    suggestedQueries: [
      {
        label: 'Challenge: Count orders per customer',
        sql: `SELECT c.id, c.first_name, c.last_name, COUNT(o.id) as order_count\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.id, c.first_name, c.last_name\nORDER BY order_count DESC;`,
        difficulty: 'intermediate',
        concept: 'JOIN trap',
        checkable: true,
        requiredClauses: ['LEFT JOIN'],
        checkOrder: true,
        trapHint: 'Your query returned fewer rows than expected. 150 customers have zero orders \u2014 INNER JOIN silently drops them. Use LEFT JOIN and COUNT(o.id) instead of COUNT(*).',
        correctHint: 'Correct! LEFT JOIN keeps all 500 customers including those with no orders. COUNT(o.id) returns 0 for unmatched rows.',
      },
      {
        label: 'Challenge: Average order value by status',
        sql: `SELECT status,\n  COUNT(*) as order_count,\n  ROUND(AVG(total)::numeric, 2) as avg_total,\n  ROUND(AVG(CASE WHEN total > 0 THEN total END)::numeric, 2) as avg_positive\nFROM orders\nGROUP BY status\nORDER BY order_count DESC;`,
        difficulty: 'intermediate',
        concept: 'Aggregation trap',
        checkable: true,
        requiredClauses: ['GROUP BY', 'CASE'],
        trapHint: 'Cancelled orders have total=$0 and returned orders have negative totals. A plain AVG includes these, distorting your analysis. Use CASE WHEN to isolate positive values.',
        correctHint: 'You correctly separated raw averages from positive-only averages \u2014 essential for real analytics where data contains special status values.',
      },
      {
        label: 'Challenge: Find unshipped orders',
        sql: `SELECT COUNT(*) as unshipped\nFROM orders\nWHERE shipped_at IS NULL;`,
        difficulty: 'beginner',
        concept: 'NULL trap',
        checkable: true,
        requiredClauses: ['IS NULL'],
        trapHint: 'Did you use WHERE shipped_at != NULL or = NULL? In SQL, NULL comparisons with = or != always return UNKNOWN. Use IS NULL or IS NOT NULL instead.',
        correctHint: 'Correct! IS NULL is the only reliable way to test for NULL values in SQL. This is the most common beginner mistake.',
      },
      {
        label: 'Challenge: Top spenders by name',
        sql: `SELECT c.id, c.first_name, c.last_name, c.email,\n  SUM(o.total) as total_spent\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nGROUP BY c.id, c.first_name, c.last_name, c.email\nORDER BY total_spent DESC\nLIMIT 10;`,
        difficulty: 'advanced',
        concept: 'Duplicate name trap',
        checkable: true,
        requiredClauses: ['GROUP BY'],
        checkOrder: true,
        trapHint: 'There are two "John Smith" and two "Maria Garcia" customers with different IDs. GROUP BY name alone merges their spending. Always GROUP BY the primary key (id).',
        correctHint: 'You correctly grouped by ID, keeping duplicate names separate. In production, never assume names are unique \u2014 always use the primary key for grouping.',
      },
      {
        label: 'Challenge: Monthly revenue (complete timeline)',
        sql: `WITH months AS (\n  SELECT generate_series(\n    DATE_TRUNC('month', MIN(created_at)),\n    DATE_TRUNC('month', MAX(created_at)),\n    '1 month'\n  )::date as month\n  FROM orders\n)\nSELECT m.month,\n  COALESCE(SUM(CASE WHEN o.status = 'delivered' THEN o.total END), 0) as revenue\nFROM months m\nLEFT JOIN orders o ON DATE_TRUNC('month', o.created_at)::date = m.month\nGROUP BY m.month\nORDER BY m.month;`,
        difficulty: 'advanced',
        concept: 'Temporal gap trap',
        checkable: true,
        requiredClauses: ['generate_series', 'LEFT JOIN', 'COALESCE'],
        checkOrder: true,
        trapHint: 'Feb and Aug 2024 have zero delivered orders, plus a 3-week gap (Dec 15 \u2013 Jan 5). GROUP BY month from orders drops these gaps. Use generate_series for a complete date range.',
        correctHint: 'Excellent! generate_series creates every month, LEFT JOIN preserves gaps, and COALESCE fills them with $0. Essential for time-series reporting.',
      },
      {
        label: 'Challenge: Calculate net revenue per order',
        sql: `SELECT oi.order_id,\n  SUM(oi.unit_price_cents * oi.quantity) / 100.0 as subtotal,\n  SUM(oi.discount_cents) / 100.0 as total_discount,\n  SUM(GREATEST(oi.unit_price_cents * oi.quantity - oi.discount_cents, 0)) / 100.0 as safe_net\nFROM order_items oi\nGROUP BY oi.order_id\nORDER BY safe_net ASC\nLIMIT 20;`,
        difficulty: 'intermediate',
        concept: 'Over-discount trap',
        checkable: true,
        requiredClauses: ['GREATEST', 'GROUP BY'],
        checkOrder: true,
        trapHint: 'Some line items have discount_cents > subtotal (an over-discounting data bug). Naive subtraction gives negative line-item revenue. Use GREATEST(..., 0) to floor at zero, or filter out bad data.',
        correctHint: 'You caught the over-discount bug! GREATEST floors negative line items at zero. In production, also flag these for data quality review.',
      },
      {
        label: 'Challenge: Find highest-rated products',
        sql: `SELECT p.name, p.category,\n  ROUND(AVG(r.rating)::numeric, 2) as avg_rating,\n  COUNT(r.id) as review_count,\n  ROUND(AVG(CASE WHEN r.is_verified THEN r.rating END)::numeric, 2) as verified_avg\nFROM products p\nJOIN reviews r ON r.product_id = p.id\nGROUP BY p.id, p.name, p.category\nHAVING COUNT(r.id) >= 3\nORDER BY verified_avg DESC NULLS LAST\nLIMIT 10;`,
        difficulty: 'intermediate',
        concept: 'Fake review trap',
        checkable: true,
        requiredClauses: ['is_verified', 'HAVING'],
        trapHint: '25 reviews have 5-star ratings but body text contains "terrible" and "broken" \u2014 fake reviews with is_verified=false. Filter by is_verified or cross-check sentiment.',
        correctHint: 'You filtered fake reviews using is_verified! In production, combine verified status with sentiment analysis for robust review quality.',
      },
      {
        label: 'Challenge: Rank suppliers by reliability',
        sql: `SELECT s.name, s.country, s.reliability_score,\n  COUNT(p.id) as product_count\nFROM suppliers s\nLEFT JOIN products p ON p.supplier_id = s.id\nGROUP BY s.id, s.name, s.country, s.reliability_score\nORDER BY s.reliability_score ASC NULLS LAST;`,
        difficulty: 'beginner',
        concept: 'NULL vs ZERO trap',
        checkable: true,
        requiredClauses: ['NULLS LAST'],
        trapHint: 'Three suppliers have NULL reliability_score (new, not unreliable). ORDER BY ASC puts NULLs first in PostgreSQL, hiding truly low-scoring suppliers. Use NULLS LAST or COALESCE.',
        correctHint: 'Correct! NULLS LAST separates unknown from low-scoring. In analytics, NULL means "no data" \u2014 never treat it as zero.',
      },
      {
        label: 'Challenge: Verify inventory balances',
        sql: `WITH running AS (\n  SELECT il.*,\n    p.name as product_name,\n    SUM(il.quantity_change) OVER (\n      PARTITION BY il.product_id ORDER BY il.id\n    ) as calculated_balance\n  FROM inventory_log il\n  JOIN products p ON p.id = il.product_id\n)\nSELECT product_id, product_name, change_type,\n  quantity_change, calculated_balance, balance_after,\n  calculated_balance - balance_after as discrepancy\nFROM running\nWHERE calculated_balance != balance_after\nORDER BY ABS(calculated_balance - balance_after) DESC;`,
        difficulty: 'advanced',
        concept: 'Running total trap',
        checkable: true,
        requiredClauses: ['OVER', 'PARTITION BY'],
        trapHint: 'The balance_after column was corrupted by adjustment entries. Use SUM() OVER (PARTITION BY product_id ORDER BY id) to recompute the running balance and find where it diverges from the stored value.',
        correctHint: 'You used a window function to recompute running balances and identify discrepancies \u2014 a critical audit skill for financial and inventory systems.',
      },
      {
        label: 'Challenge: Customer conversion funnel',
        sql: `SELECT\n  COUNT(DISTINCT customer_id) as total_customers,\n  COUNT(DISTINCT CASE WHEN event_type = 'page_view' THEN customer_id END) as viewed,\n  COUNT(DISTINCT CASE WHEN event_type = 'add_to_cart' THEN customer_id END) as carted,\n  COUNT(DISTINCT CASE WHEN event_type = 'checkout_start' THEN customer_id END) as checkout,\n  COUNT(DISTINCT CASE WHEN event_type = 'purchase' THEN customer_id END) as purchased,\n  COUNT(DISTINCT CASE WHEN event_type = 'abandon' THEN customer_id END) as abandoned\nFROM customer_events;`,
        difficulty: 'advanced',
        concept: 'Funnel drop-off trap',
        checkable: true,
        requiredClauses: ['COUNT(DISTINCT', 'CASE WHEN'],
        trapHint: 'Naive COUNT(*) GROUP BY event_type counts events, not customers. Some customers have multiple page_views, some skip stages entirely. Use COUNT(DISTINCT customer_id) with CASE WHEN for accurate funnel metrics.',
        correctHint: 'You correctly counted unique customers per funnel stage, not raw events. This reveals the true drop-off rate at each stage.',
      },
    ],
  },
];
