import type { CourseDefinition } from '../courseRegistry.js';

export const analyticsIntroCourse: CourseDefinition = {
  name: 'analytics-intro',
  displayName: 'Analytics Introduction',
  description: 'Learn analytics SQL: aggregation, window functions, CTEs, and reporting patterns.',
  difficulty: 'intermediate',
  estimatedMinutes: 120,
  schemaDDL: [
    `CREATE TABLE IF NOT EXISTS classroom_sales_reps (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      region VARCHAR(60) NOT NULL,
      hire_date DATE NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS classroom_sales (
      id SERIAL PRIMARY KEY,
      rep_id INTEGER REFERENCES classroom_sales_reps(id),
      deal_date DATE NOT NULL,
      amount NUMERIC(12,2) NOT NULL,
      product_line VARCHAR(60) NOT NULL,
      quarter VARCHAR(10) NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS classroom_page_views (
      id SERIAL PRIMARY KEY,
      page_path VARCHAR(200) NOT NULL,
      visitor_id VARCHAR(60) NOT NULL,
      view_date DATE NOT NULL,
      duration_seconds INTEGER NOT NULL,
      referrer VARCHAR(100)
    )`,
  ],
  seedSQL: [
    `INSERT INTO classroom_sales_reps (name, region, hire_date) VALUES
      ('Sarah Connor', 'West', '2024-01-15'),
      ('John Reese', 'East', '2024-03-20'),
      ('Kyle Stone', 'West', '2024-06-01'),
      ('Maria Santos', 'Central', '2023-11-10'),
      ('James Park', 'East', '2024-08-05'),
      ('Lisa Wang', 'Central', '2024-02-28')`,
    `INSERT INTO classroom_sales (rep_id, deal_date, amount, product_line, quarter) VALUES
      (1, '2025-01-10', 15000, 'Enterprise', 'Q1'),
      (1, '2025-02-14', 8500, 'Pro', 'Q1'),
      (2, '2025-01-22', 12000, 'Enterprise', 'Q1'),
      (3, '2025-02-05', 3200, 'Starter', 'Q1'),
      (4, '2025-03-01', 22000, 'Enterprise', 'Q1'),
      (1, '2025-03-18', 9500, 'Pro', 'Q1'),
      (2, '2025-04-02', 18000, 'Enterprise', 'Q2'),
      (5, '2025-04-15', 4800, 'Pro', 'Q2'),
      (6, '2025-04-28', 7200, 'Pro', 'Q2'),
      (3, '2025-05-10', 2100, 'Starter', 'Q2'),
      (4, '2025-05-22', 28000, 'Enterprise', 'Q2'),
      (1, '2025-06-01', 11000, 'Enterprise', 'Q2'),
      (2, '2025-06-15', 6500, 'Pro', 'Q2'),
      (6, '2025-07-03', 19500, 'Enterprise', 'Q3'),
      (5, '2025-07-20', 3800, 'Starter', 'Q3'),
      (3, '2025-08-05', 14200, 'Enterprise', 'Q3'),
      (4, '2025-08-18', 9800, 'Pro', 'Q3'),
      (1, '2025-09-01', 25000, 'Enterprise', 'Q3'),
      (2, '2025-09-15', 5200, 'Pro', 'Q3'),
      (6, '2025-09-28', 16800, 'Enterprise', 'Q3')`,
    `INSERT INTO classroom_page_views (page_path, visitor_id, view_date, duration_seconds, referrer) VALUES
      ('/home', 'v001', '2025-06-01', 45, 'google'),
      ('/pricing', 'v001', '2025-06-01', 120, NULL),
      ('/features', 'v002', '2025-06-01', 30, 'google'),
      ('/home', 'v003', '2025-06-02', 15, 'twitter'),
      ('/blog/sql-tips', 'v002', '2025-06-02', 180, 'google'),
      ('/pricing', 'v003', '2025-06-02', 90, NULL),
      ('/signup', 'v001', '2025-06-03', 60, NULL),
      ('/home', 'v004', '2025-06-03', 25, 'linkedin'),
      ('/features', 'v004', '2025-06-03', 55, NULL),
      ('/pricing', 'v004', '2025-06-04', 110, NULL),
      ('/blog/sql-tips', 'v005', '2025-06-04', 200, 'google'),
      ('/signup', 'v004', '2025-06-05', 40, NULL),
      ('/home', 'v006', '2025-06-05', 20, 'twitter'),
      ('/blog/analytics', 'v006', '2025-06-06', 150, 'google'),
      ('/pricing', 'v006', '2025-06-06', 95, NULL)`,
  ],
  exercises: [
    {
      id: 'revenue-by-quarter',
      title: 'Revenue by Quarter',
      description: 'Calculate total revenue for each quarter. Order by quarter.',
      difficulty: 'beginner',
      hint: 'SELECT quarter, SUM(amount) AS revenue FROM classroom_sales GROUP BY quarter ORDER BY quarter;',
      tables: ['classroom_sales'],
      expectedConcept: 'GROUP BY with SUM',
    },
    {
      id: 'top-performers',
      title: 'Top Performers',
      description: 'Find the top 3 sales reps by total revenue. Show name and total.',
      difficulty: 'intermediate',
      hint: 'SELECT r.name, SUM(s.amount) AS total FROM classroom_sales s JOIN classroom_sales_reps r ON s.rep_id = r.id GROUP BY r.name ORDER BY total DESC LIMIT 3;',
      tables: ['classroom_sales', 'classroom_sales_reps'],
      expectedConcept: 'GROUP BY + ORDER BY + LIMIT',
    },
    {
      id: 'running-total',
      title: 'Running Total',
      description: 'Calculate a running total of sales amount ordered by deal_date.',
      difficulty: 'intermediate',
      hint: 'SELECT deal_date, amount, SUM(amount) OVER (ORDER BY deal_date) AS running_total FROM classroom_sales;',
      tables: ['classroom_sales'],
      expectedConcept: 'Window function SUM OVER',
    },
    {
      id: 'rank-by-region',
      title: 'Rank Reps by Region',
      description: 'Rank each sales rep within their region by total revenue.',
      difficulty: 'intermediate',
      hint: 'SELECT r.name, r.region, SUM(s.amount) AS total, RANK() OVER (PARTITION BY r.region ORDER BY SUM(s.amount) DESC) AS rank FROM classroom_sales s JOIN classroom_sales_reps r ON s.rep_id = r.id GROUP BY r.name, r.region;',
      tables: ['classroom_sales', 'classroom_sales_reps'],
      expectedConcept: 'RANK with PARTITION BY',
    },
    {
      id: 'quarter-over-quarter',
      title: 'Quarter-over-Quarter Growth',
      description: 'Calculate the revenue change between consecutive quarters using LAG.',
      difficulty: 'advanced',
      hint: "WITH quarterly AS (SELECT quarter, SUM(amount) AS revenue FROM classroom_sales GROUP BY quarter) SELECT quarter, revenue, LAG(revenue) OVER (ORDER BY quarter) AS prev_quarter, revenue - LAG(revenue) OVER (ORDER BY quarter) AS growth FROM quarterly;",
      tables: ['classroom_sales'],
      expectedConcept: 'CTE + LAG window function',
    },
    {
      id: 'page-funnel',
      title: 'Page View Funnel',
      description: 'Count unique visitors for each page path. Show as a conversion funnel (home → pricing → signup).',
      difficulty: 'intermediate',
      hint: "SELECT page_path, COUNT(DISTINCT visitor_id) AS unique_visitors FROM classroom_page_views GROUP BY page_path ORDER BY unique_visitors DESC;",
      tables: ['classroom_page_views'],
      expectedConcept: 'COUNT DISTINCT',
    },
    {
      id: 'avg-time-on-page',
      title: 'Average Time on Page',
      description: 'Calculate the average duration in seconds for each page, along with total views.',
      difficulty: 'beginner',
      hint: 'SELECT page_path, COUNT(*) AS views, ROUND(AVG(duration_seconds), 1) AS avg_duration FROM classroom_page_views GROUP BY page_path ORDER BY avg_duration DESC;',
      tables: ['classroom_page_views'],
      expectedConcept: 'AVG aggregate',
    },
    {
      id: 'referrer-attribution',
      title: 'Referrer Attribution with CTE',
      description: 'Using a CTE, find which referrer source drives the most engaged visitors (highest average duration).',
      difficulty: 'advanced',
      hint: "WITH referred AS (SELECT referrer, visitor_id, duration_seconds FROM classroom_page_views WHERE referrer IS NOT NULL) SELECT referrer, COUNT(DISTINCT visitor_id) AS visitors, ROUND(AVG(duration_seconds), 1) AS avg_duration FROM referred GROUP BY referrer ORDER BY avg_duration DESC;",
      tables: ['classroom_page_views'],
      expectedConcept: 'CTE with filtered aggregation',
    },
  ],
};
