import type { CourseDefinition } from '../courseRegistry.js';

export const sql101Course: CourseDefinition = {
  name: 'sql-101',
  displayName: 'SQL 101',
  description: 'Learn SQL fundamentals from SELECT to JOINs. Perfect for beginners with no SQL experience.',
  difficulty: 'beginner',
  estimatedMinutes: 90,
  schemaDDL: [
    `CREATE TABLE IF NOT EXISTS classroom_customers (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(150) NOT NULL,
      city VARCHAR(80),
      country VARCHAR(60) DEFAULT 'US',
      signup_date DATE NOT NULL,
      is_active BOOLEAN DEFAULT true
    )`,
    `CREATE TABLE IF NOT EXISTS classroom_products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(120) NOT NULL,
      category VARCHAR(60) NOT NULL,
      price NUMERIC(10,2) NOT NULL,
      stock_quantity INTEGER DEFAULT 0,
      created_at DATE NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS classroom_orders (
      id SERIAL PRIMARY KEY,
      customer_id INTEGER REFERENCES classroom_customers(id),
      order_date DATE NOT NULL,
      total NUMERIC(10,2) NOT NULL,
      status VARCHAR(30) DEFAULT 'pending'
    )`,
    `CREATE TABLE IF NOT EXISTS classroom_order_items (
      id SERIAL PRIMARY KEY,
      order_id INTEGER REFERENCES classroom_orders(id),
      product_id INTEGER REFERENCES classroom_products(id),
      quantity INTEGER NOT NULL,
      unit_price NUMERIC(10,2) NOT NULL
    )`,
  ],
  seedSQL: [
    // Customers
    `INSERT INTO classroom_customers (name, email, city, country, signup_date, is_active) VALUES
      ('Alice Johnson', 'alice@example.com', 'New York', 'US', '2025-01-15', true),
      ('Bob Smith', 'bob@example.com', 'London', 'UK', '2025-02-20', true),
      ('Carol Martinez', 'carol@example.com', 'Madrid', 'ES', '2025-03-10', true),
      ('David Lee', 'david@example.com', 'Toronto', 'CA', '2025-04-05', false),
      ('Emma Wilson', 'emma@example.com', 'Sydney', 'AU', '2025-05-18', true),
      ('Frank Brown', 'frank@example.com', 'Berlin', 'DE', '2025-06-22', true),
      ('Grace Kim', 'grace@example.com', 'Seoul', 'KR', '2025-07-01', false),
      ('Henry Davis', 'henry@example.com', 'New York', 'US', '2025-08-14', true),
      ('Ivy Chen', 'ivy@example.com', 'Tokyo', 'JP', '2025-09-30', true),
      ('Jack Taylor', 'jack@example.com', 'London', 'UK', '2025-10-11', true)`,
    // Products
    `INSERT INTO classroom_products (name, category, price, stock_quantity, created_at) VALUES
      ('Laptop Pro 15', 'Electronics', 1299.99, 50, '2025-01-01'),
      ('Wireless Mouse', 'Electronics', 29.99, 200, '2025-01-01'),
      ('USB-C Hub', 'Electronics', 49.99, 150, '2025-02-01'),
      ('Standing Desk', 'Furniture', 599.00, 30, '2025-02-15'),
      ('Ergonomic Chair', 'Furniture', 449.00, 45, '2025-03-01'),
      ('Notebook Set', 'Office', 12.99, 500, '2025-01-10'),
      ('Desk Lamp', 'Office', 34.99, 120, '2025-04-01'),
      ('Monitor 27"', 'Electronics', 399.99, 75, '2025-05-01'),
      ('Keyboard Mechanical', 'Electronics', 89.99, 180, '2025-03-15'),
      ('Webcam HD', 'Electronics', 69.99, 100, '2025-06-01')`,
    // Orders
    `INSERT INTO classroom_orders (customer_id, order_date, total, status) VALUES
      (1, '2025-03-01', 1329.98, 'completed'),
      (2, '2025-03-15', 599.00, 'completed'),
      (3, '2025-04-02', 79.98, 'completed'),
      (1, '2025-04-20', 449.00, 'completed'),
      (5, '2025-05-10', 1749.98, 'shipped'),
      (4, '2025-05-25', 34.99, 'cancelled'),
      (6, '2025-06-01', 159.98, 'pending'),
      (8, '2025-06-15', 489.98, 'completed'),
      (2, '2025-07-01', 12.99, 'completed'),
      (9, '2025-07-20', 1299.99, 'shipped'),
      (10, '2025-08-05', 539.98, 'pending'),
      (3, '2025-08-18', 89.99, 'completed')`,
    // Order items
    `INSERT INTO classroom_order_items (order_id, product_id, quantity, unit_price) VALUES
      (1, 1, 1, 1299.99),
      (1, 2, 1, 29.99),
      (2, 4, 1, 599.00),
      (3, 3, 1, 49.99),
      (3, 2, 1, 29.99),
      (4, 5, 1, 449.00),
      (5, 1, 1, 1299.99),
      (5, 5, 1, 449.00),
      (6, 7, 1, 34.99),
      (7, 9, 1, 89.99),
      (7, 10, 1, 69.99),
      (8, 8, 1, 399.99),
      (8, 9, 1, 89.99),
      (9, 6, 1, 12.99),
      (10, 1, 1, 1299.99),
      (11, 4, 1, 599.00),
      (12, 9, 1, 89.99)`,
  ],
  exercises: [
    {
      id: 'select-basics',
      title: 'Your First SELECT',
      description: 'Retrieve all columns from the classroom_customers table.',
      difficulty: 'beginner',
      hint: 'SELECT * FROM classroom_customers;',
      tables: ['classroom_customers'],
      expectedConcept: 'SELECT *',
    },
    {
      id: 'select-columns',
      title: 'Selecting Specific Columns',
      description: 'Retrieve only the name and email columns from classroom_customers.',
      difficulty: 'beginner',
      hint: 'SELECT name, email FROM classroom_customers;',
      tables: ['classroom_customers'],
      expectedConcept: 'SELECT columns',
    },
    {
      id: 'where-filter',
      title: 'Filtering with WHERE',
      description: 'Find all customers from the US.',
      difficulty: 'beginner',
      hint: "SELECT * FROM classroom_customers WHERE country = 'US';",
      tables: ['classroom_customers'],
      expectedConcept: 'WHERE clause',
    },
    {
      id: 'where-multiple',
      title: 'Multiple Conditions',
      description: 'Find active customers who signed up after June 2025.',
      difficulty: 'beginner',
      hint: "SELECT * FROM classroom_customers WHERE is_active = true AND signup_date > '2025-06-01';",
      tables: ['classroom_customers'],
      expectedConcept: 'AND/OR operators',
    },
    {
      id: 'order-by',
      title: 'Sorting Results',
      description: 'List all products sorted by price from highest to lowest.',
      difficulty: 'beginner',
      hint: 'SELECT * FROM classroom_products ORDER BY price DESC;',
      tables: ['classroom_products'],
      expectedConcept: 'ORDER BY',
    },
    {
      id: 'count-group',
      title: 'Counting and Grouping',
      description: 'Count how many products exist in each category.',
      difficulty: 'intermediate',
      hint: 'SELECT category, COUNT(*) FROM classroom_products GROUP BY category;',
      tables: ['classroom_products'],
      expectedConcept: 'GROUP BY + COUNT',
    },
    {
      id: 'aggregate-sum',
      title: 'Aggregation Functions',
      description: 'Find the total revenue (sum of order totals) for completed orders.',
      difficulty: 'intermediate',
      hint: "SELECT SUM(total) FROM classroom_orders WHERE status = 'completed';",
      tables: ['classroom_orders'],
      expectedConcept: 'SUM aggregate',
    },
    {
      id: 'inner-join',
      title: 'Your First JOIN',
      description: 'List all orders with the customer name. Show customer name, order date, and total.',
      difficulty: 'intermediate',
      hint: 'SELECT c.name, o.order_date, o.total FROM classroom_orders o JOIN classroom_customers c ON o.customer_id = c.id;',
      tables: ['classroom_orders', 'classroom_customers'],
      expectedConcept: 'INNER JOIN',
    },
    {
      id: 'multi-join',
      title: 'Multi-Table JOIN',
      description: 'List each order item with the product name, customer name, quantity, and unit price.',
      difficulty: 'advanced',
      hint: 'SELECT c.name AS customer, p.name AS product, oi.quantity, oi.unit_price FROM classroom_order_items oi JOIN classroom_orders o ON oi.order_id = o.id JOIN classroom_customers c ON o.customer_id = c.id JOIN classroom_products p ON oi.product_id = p.id;',
      tables: ['classroom_order_items', 'classroom_orders', 'classroom_customers', 'classroom_products'],
      expectedConcept: 'Multi-table JOIN',
    },
    {
      id: 'subquery',
      title: 'Subqueries',
      description: 'Find customers who have placed orders totaling more than $500.',
      difficulty: 'advanced',
      hint: 'SELECT name FROM classroom_customers WHERE id IN (SELECT customer_id FROM classroom_orders GROUP BY customer_id HAVING SUM(total) > 500);',
      tables: ['classroom_customers', 'classroom_orders'],
      expectedConcept: 'Subquery with IN',
    },
  ],
};
